print('What is your name?')
name = input()
print('Nice to meet you, '+ name)
print('The length of your name is:')
print(len(name))
print('What is your age?')
age = input()
print('You will be ' + str(int(age) + 1) + ' in a year.')